ALTER TABLE MCUSER
DROP CONSTRAINT FK_MCUserCountry;

ALTER TABLE MCUSER
DROP CONSTRAINT FK_MCUser_University;

ALTER TABLE MCUSER
DROP CONSTRAINT FK_MCUser_State;

ALTER TABLE MCUSER_ADMIN
DROP CONSTRAINT FK_MCUSER_ADMIN_State;

ALTER TABLE USER_GENRE_LIST
DROP CONSTRAINT FK_Genre_List_User;

ALTER TABLE USER_GENRE_LIST
DROP CONSTRAINT FK_Genre_List_Genre;

ALTER TABLE BILLBOARD
DROP CONSTRAINT FK_Billboard_Place;

ALTER TABLE BILLBOARD
DROP CONSTRAINT FK_Billboard_EventState;

ALTER TABLE FESTIVAL
DROP CONSTRAINT FK_Festival_Billboard;

ALTER TABLE FESTIVAL
DROP CONSTRAINT FK_Festival_EventState;

ALTER TABLE FESTIVAL
DROP CONSTRAINT FK_FESTIVAL_Place;

ALTER TABLE USER_VOTE
DROP CONSTRAINT FK_USER_VOTE_Billboard;

ALTER TABLE USER_VOTE
DROP CONSTRAINT FK_USER_VOTE_User;

ALTER TABLE CATEGORY_LIST
DROP CONSTRAINT FK_ID_CATEGORY_LIST_Billboard;

ALTER TABLE CATEGORY_LIST
DROP CONSTRAINT FK_ID_CATEGORY_LIST_BillboardCategory;

ALTER TABLE BILLBOARD_CATEGORY
DROP CONSTRAINT FK_BILLBOARD_CATEGORY_Category

ALTER TABLE FESTIVAL_CATEGORY
DROP CONSTRAINT FK_FESTIVAL_CATEGORY_Category;

ALTER TABLE FESTIVAL_CATEGORY_LIST
DROP CONSTRAINT FK_FESTIVAL_CATEGORY_LIST_Festival;

ALTER TABLE FESTIVAL_CATEGORY_LIST
DROP CONSTRAINT FK_FESTIVAL_CATEGORY_LIST_FestivalCategory;

ALTER TABLE FESTIVAL_BANDS_LIST
DROP CONSTRAINT FK_FESTIVAL_BANDS_LIST_FestivalCategory;

ALTER TABLE FESTIVAL_BANDS_LIST
DROP CONSTRAINT FK_FESTIVAL_BANDS_LIST_Band;

ALTER TABLE BILLBOARD_BANDS_LIST
DROP CONSTRAINT FK_BILLBOARD_BANDS_LIST_BillboardCategory;

ALTER TABLE BILLBOARD_BANDS_LIST
DROP CONSTRAINT FK_BILLBOARD_BANDS_LIST_Band;

ALTER TABLE BAND_GENRE_LIST
DROP CONSTRAINT FK_BAND_GENRE_LIST_Band;

ALTER TABLE BAND_GENRE_LIST
DROP CONSTRAINT FK_BAND_GENRE_LIST_Genre

ALTER TABLE BAND_ARTIST
DROP CONSTRAINT FK_BAND_ARTIST_Artist;

ALTER TABLE BAND_ARTIST
DROP CONSTRAINT FK_BAND_ARTIST_Band;

ALTER TABLE COMMENT_LIST
DROP CONSTRAINT FK_COMMMENT_LIST_Band;

ALTER TABLE COMMENT_LIST
DROP CONSTRAINT FK_COMMENT_LIST_Comment;

ALTER TABLE COMMENT
DROP CONSTRAINT FK_COMMENT_User;

ALTER TABLE SONG_LIST
DROP CONSTRAINT FK_SONG_LIST_Band

ALTER TABLE SONG_LIST
DROP CONSTRAINT FK_SONG_LIST_Song



DROP TABLE COUNTRY;

DROP TABLE UNIVERSITY;

DROP TABLE MCUSER;

DROP TABLE USER_STATE;

DROP TABLE USER_GENRE_LIST;

DROP TABLE MCUSER_ADMIN;

DROP TABLE PLACE;

DROP TABLE BILLBOARD;

DROP TABLE USER_VOTE;

DROP TABLE CATEGORY_LIST;

DROP TABLE BILLBOARD_CATEGORY;

DROP TABLE CATEGORY;

DROP TABLE BILLBOARD_BANDS_LIST;

DROP TABLE BAND;

DROP TABLE BAND_GENRE_LIST;

DROP TABLE BAND_ARTIST;

DROP TABLE ARTIST;

DROP TABLE GENRE;

DROP TABLE COMMENT;

DROP TABLE COMMENT_LIST;

DROP TABLE FESTIVAL;

DROP TABLE FESTIVAL_CATEGORY_LIST;

DROP TABLE FESTIVAL_BANDS_LIST;

DROP TABLE FESTIVAL_CATEGORY;

DROP TABLE EVENT_STATE;



DROP PROCEDURE spLogin;

DROP PROCEDURE spRegisterUser;

DROP PROCEDURE spRegisterAdmin;



